name: Deploy backend
run-name: Deploy backend

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - backend/**
      - .github/workflows/backend.yaml

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v7
        with:
          context: "{{defaultContext}}:backend"
          push: true
          tags: ghcr.io/${{ github.repository }}:latest

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Deploy
        uses: medvesek/infrastructure/github-actions/lkwdeploy@master
        with:
          cloudflare-token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          server-ip: ${{ secrets.AQUILA_IP }}
          ssh-user: ${{ secrets.SSH_USER }}
          ssh-private-key: ${{ secrets.SSH_KEY_PRIVATE_GITHUB_ACTIONS }}
          config: backend/lkw.yaml
